name: Generate Manifest

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - '**.lua'
      - '**/help/*.txt'
      - '**/deps.json'
      - '!install.lua'

env:
  MODULES: |-
    src

jobs:
  manifest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Generate Manifest
      run: |-
        for module in $MODULES; do
          echo "Generate manifest for /${module}..."
          cd ${GITHUB_WORKSPACE}/${module}
          bash ${GITHUB_WORKSPACE}/.bin/manifest.sh
        done

    - name: Commit Changes
      run: |-
        git config user.name github-actions
        git config user.email github-actions@github.com

        for module in $MODULES; do
          git add ${GITHUB_WORKSPACE}/${module}/manifest.json
        done

        git commit -m "Generate new manifest"
        git push
